# Data Manipulation and Analysis with Pandas

A walkthrough of common pandas operations: inspecting data, handling missing values, renaming columns, changing data types, grouping/aggregating, and merging DataFrames.

## 1. Setup

In [1]:
import pandas as pd

## 2. Loading and Inspecting the Data

In [9]:
df = pd.read_csv('data.csv')

## Fetch first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [10]:
# Last 2 rows
df.tail(2)

          Date Category  Value   Product  Sales Region
98  2023-04-09        B   52.9  Product3  582.6   East
99  2023-04-10        A   29.6  Product3  338.9   East

In [11]:
df.describe()

           Value       Sales
count  89.000000   92.000000
mean   49.602247  580.726087
std    27.065757  254.394135
min     2.000000  108.000000
25%    27.000000  357.975000
50%    50.000000  586.000000
75%    71.000000  826.400000
max    98.900000  997.600000

In [12]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

## 3. Handling Missing Values

In [13]:
df.isnull()

# Missing = True     |     Not Missing = False

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
..    ...       ...    ...      ...    ...     ...
95  False     False  False    False  False   False
96  False     False  False    False  False   False
97  False     False   True    False  False   False
98  False     False  False    False  False   False
99  False     False  False    False  False   False

[100 rows x 6 columns]

In [14]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [15]:
df.isnull().sum()

Date         0
Category     0
Value       11
Product      0
Sales        8
Region       0
dtype: int64

### Filling Missing Values with a Constant

In [18]:
## Fill the missing values with data

df_filled = df.fillna(0)    # replace with 0
df_filled

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
..         ...      ...    ...       ...    ...    ...
95  2023-04-06        C   81.2  Product2  731.2  South
96  2023-04-07        A   25.9  Product2  838.5   West
97  2023-04-08        A    0.0  Product1  350.7   East
98  2023-04-09        B   52.9  Product3  582.6   East
99  2023-04-10        A   29.6  Product3  338.9   East

[100 rows x 6 columns]

### Filling Missing Values with the Column Mean

In [19]:
### Filling missing values with the mean of the column

## Fill the missing sales with it's mean
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())

df      # Creates new Collumn - Sales_fillNA : and stores mean of Sales

          Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East         754.0
1   2023-01-02        B   39.0  Product3  110.0  North         110.0
2   2023-01-03        C   32.0  Product2  398.0   East         398.0
3   2023-01-04        B    8.0  Product1  522.0   East         522.0
4   2023-01-05        B   26.0  Product3  869.0  North         869.0
..         ...      ...    ...       ...    ...    ...           ...
95  2023-04-06        C   81.2  Product2  731.2  South         731.2
96  2023-04-07        A   25.9  Product2  838.5   West         838.5
97  2023-04-08        A    NaN  Product1  350.7   East         350.7
98  2023-04-09        B   52.9  Product3  582.6   East         582.6
99  2023-04-10        A   29.6  Product3  338.9   East         338.9

[100 rows x 7 columns]

In [20]:
df.dtypes

Date                str
Category            str
Value           float64
Product             str
Sales           float64
Region              str
Sales_fillNA    float64
dtype: object

## 4. Renaming Columns

In [23]:
df = df.rename(columns = {'Date' : 'Sales Date'})

df.head(3)

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0

## 5. Changing Data Types

In [26]:
df['value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)

df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA  value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

### Creating a New Column from an Existing One

In [27]:
df['New Value'] = df['Value'].apply(lambda x:x*2)

df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

## 6. Grouping and Aggregating Data

In [28]:
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

### Grouping by a Single Column

In [29]:
grouped_mean = df.groupby('Product')['Value'].mean()

print(grouped_mean)

Product
Product1    52.266667
Product2    49.780769
Product3    45.877778
Name: Value, dtype: float64

### Grouping by Multiple Columns

In [30]:
grouped_sum = df.groupby(['Product', 'Region'])['Value'].sum()

print(grouped_sum)

Product   Region
Product1  East      469.3
          North     376.2
          South     198.5
          West      837.6
Product2  East      165.5
          North     225.8
          South     438.3
          West      464.7
Product3  East      373.6
          North     166.2
          South     403.2
          West      295.7
Name: Value, dtype: float64

In [31]:
df.groupby(['Product', 'Region'])['Value'].mean()

Product   Region
Product1  East      39.108333
          North     47.025000
          South     66.166667
          West      64.430769
Product2  East      33.100000
          North     56.450000
          South     62.614286
          West      46.470000
Product3  East      41.511111
          North     33.240000
          South     57.600000
          West      49.283333
Name: Value, dtype: float64

### Aggregating with Multiple Functions

In [33]:
##  Agregate Multiple Functions

grouped_agg = df.groupby('Region')['Value'].agg(['sum', 'mean', 'count'])

grouped_agg

           sum       mean  count
Region
East    1008.4  38.784615     26
North    768.2  45.188235     17
South   1040.0  61.176471     17
West    1598.0  55.103448     29

## 7. Merging and Joining DataFrames

### Sample DataFrames

In [34]:
# Create a simple DataFrames

df1 = pd.DataFrame({'Key' : ['A', 'B', 'C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'Key' : ['A', 'B', 'D'], 'Value2': [4,5,6]})

In [35]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [36]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

### Inner Join

In [39]:
## Marge DataFrame on the 'Key Columns'

pd.merge(df1, df2, on="Key", how="inner")    ## Inner Join

  Key  Value1  Value2
0   A       1       4
1   B       2       5

### Outer Join

In [40]:
pd.merge(df1, df2, on="Key", how="outer")    ## Outer Join

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

### Left Join

In [41]:
pd.merge(df1, df2, on="Key", how="left")     ## Left Outer Join

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

### Right Join

In [42]:
pd.merge(df1, df2, on="Key", how="right")     ## Right Outer Join

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6